version: '3'
services:

  nginx:
    hostname: nginx
    build:
      context: ./df/nginx
      dockerfile: Dockerfile
    ports:
      - "9001:80"
    networks:
      - npm_net
    depends_on:
      - flask
    volumes:
      - ./log/nginx/:/log:rw
      - ./sock:/sock
      - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
    restart: always
    command: |
      sh -c '
      /usr/sbin/nginx'

  flask:
    hostname: flask
    build:
      context: ./df/flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - npm_net
    depends_on:
      - mongodb
    volumes:
      - ./log/flask:/log:rw
      - ./sock:/sock
      - ../../backend:/app:rw
    restart: always
    command: |
      sh -c '
      export GOOGLE_APPLICATION_CREDENTIALS="j1.json"
      cp /app/uwsgi.ini /etc/uwsgi/uwsgi.ini
      cp /app/supervisord.conf /etc/supervisord.conf
      /usr/bin/supervisord
      entrypoint.sh
      tail -f /dev/null'
 
  mongodb:
          hostname: mongodb
          image: mongo:4.0.4
          ports:
            - "27777:27017"
          networks:
            - npm_net
          volumes:     
            - ./mongo:/data/db:rw
          command: mongod --smallfiles --logpath=/dev/null # --quiet
          environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
  node:
       hostname: nodejs
       build:
         context: ./df/nodejs
         dockerfile: Dockerfile
       ports:
         - "30000:3000"
       networks:
         - npm_net
       volumes:
         - ./nodejs:/nodejs:rw
         - ./log/nodejs/:/log:rw
networks:
  npm_net:

